### ISSUE TITLE
Still developing this?

### ISSUE THREAD

**Issue by chmac** [siokas/tellots#4]
Looks like it's been a while since there was a commit. Are you still using this? Still developing it?

Thanks for making a typescript version. I didn't immediately find it, but glad I did. Noticed a broken link on npm to tellojs instead of tellots, submitting a PR now.

**Comment by siokas** [comment]
Hi. No I don't use this now. I had two failures in the tello motors (never flew outside, never hit on wall, only for educational purposes in home) and they told me that it was my fault and I couldn't use the warranty. First time if fixed myself but the second time I gave up everything!
